### ISSUE TITLE
Cannot write to Elasticsearch 6.2.4 except using messageType: '_doc'

### ISSUE THREAD

**Issue by Nagato-Yuki** [vanthome/winston-elasticsearch#49] opened 2018-05-22 06:53 UTC
When I leave messageType to default, I get this error
```
Elasticsearch index error { type: 'illegal_argument_exception',
reason: 'Rejecting mapping update to [logs-2018.05.21] as the final mapping would have more than 1 type: [_doc, log]' }
```
So I suspected that this change (https://www.elastic.co/guide/en/elasticsearch/reference/6.x/removal-of-types.html) is affected so you can't put to `logs-*/log` and you have to put to `logs-*/_doc` instead

**Comment by vanthome** [comment] 2018-05-22 06:57
This has been discussed here: https://github.com/vanthome/winston-elasticsearch/issues/43

**Comment by Nagato-Yuki** [comment] 2018-05-22 07:54
Thank you for fast response. But I've tried to came across this issue against newly installed ES instance since yesterday. I tried deleting all indices but it's not working until I found this breaking change issue. please help. I'm new to ES.

This is the code which is work.
- ES 6.2.4
- winston-elasticsearch 0.6.0
```
    const esTransportOpts = {
      level: '',
      indexPrefix: process.env.LOG_ES_PREFIX,
      messageType: '_doc',
      clientOpts: {
        host: config.LOG_ES_ENDPOINT,
        apiVersion: '6.x'
      }
    }
    _(logLevels).forEach((level) => {
      logger.add(winston.transports.ElasticSearchTransport,
        _(esTransportOpts).merge({ level }))
    })
```

**Comment by do5173** [comment] 2018-06-16 06:02
I get this error too.
```
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
```

**Comment by xuming314** [comment] 2018-06-16 06:04
I get this error too.
```
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
```

**Comment by xuming314** [comment] 2018-06-16 06:36
I fix the bug.
need modify the index-template-mapping.json in node_modules/winston-elasticsearch,
and remove "mappings" property.

remove below code in  index-template-mapping.json.
```
"mappings": {
    "_doc": {
      "_all": { "enabled": false, "omit_norms": true },
      "_source": { "enabled": true },
      "dynamic_templates": [
        {
          "string_fields": {
            "match": "*",
            "mapping": {
              "type": "text", "index": true, "omit_norms": true,
              "fields": {
                "raw": { "type": "keyword", "index": true, "ignore_above": 256 }
              }
            }
          }
        }
      ],
      "properties": {
        "@timestamp": { "type": "date" },
        "@version": { "type": "keyword" },
        "message": { "type": "text", "index": true },
        "severity": { "type": "keyword", "index": true },
        "fields": {
          "type": "object",
          "dynamic": true
        }
      }
    }
  }
```

**Comment by vanthome** [comment] 2018-06-17 21:58
ok guys, I could finally reproduce this and it's fixed with the latest release. The problem was this line: https://github.com/vanthome/winston-elasticsearch/commit/4f4755955ed63f4e76d1938d4cc2114b1832fd2b#diff-168726dbe96b3ce427e7fedce31bb0bcR32

**Closed** 2018-06-17 21:59 UTC
